version: '3'

services:

  database:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: news_feed_db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  